default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: portfolio_quiz_development
  username: postgres
  password:
  host: localhost

test:
  <<: *default
  database: portfolio_quiz_test
  username: postgres
  password:
  host: localhost

production:
  <<: *default
  database: portfolio_quiz_production
  username: postgres
  password:
  host: localhost
